version: "2"
services:
 python-app:
   image: madouk/python-app:0.1
   container_name: python1
   ports:
    - "8087:5000"
   networks:
     - cbridge
 redis:
   container_name: redis1
   image: redis
   networks:
     - cbridge
networks:
 cbridge:
   driver: bridge
